# =============================================================================================
# 매번 aws secrets에서 필요한 정보를 가져와야해서 composite로 간략화 하는 부분 및 ssh-agent 사용 부분
# =============================================================================================

name: 'Setup Ansible Environment'
description: 'AWS 인증 + SSH 키 다운로드'

inputs:
  aws-access-key-id:
    required: true
  aws-secret-access-key:
    required: true
  bastion-ssh-key:
    required: true
  ansible-ssh-key:
    required: true

runs:
  using: 'composite'
  steps:
      # 1. AWS 인증
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ap-northeast-2

    # 2. AWS Secrets Manager → ~/.ssh/ 파일 저장 (bootstrap inventory용)
    - name: Fetch SSH keys
      shell: bash
      run: |
        mkdir -p ~/.ssh && chmod 700 ~/.ssh
        for key in project01-bastion-key project01-was-key project01-db-key; do
          aws secretsmanager get-secret-value \
            --secret-id "ssh-keys/${key}" \
            --query SecretString --output text > ~/.ssh/${key}.pem
          chmod 600 ~/.ssh/${key}.pem
        done

    # 3. GitHub Secrets의 키를 ssh-agent에 등록 (dev inventory용)
    - name: Start ssh-agent and add keys
      shell: bash
      run: |
        eval "$(ssh-agent -s)"
        echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
        echo "SSH_AGENT_PID=$SSH_AGENT_PID" >> $GITHUB_ENV

        echo "${{ inputs.bastion-ssh-key }}" | ssh-add -
        echo "${{ inputs.ansible-ssh-key }}" | ssh-add -

      # ssh-add -l 디버깅용 ssh agent 목록 보기

      # 4. s3 에 저장되있는 inventory.yml 불러오기
    - name: Download inventories from S3
      shell: bash
      run: |
        mkdir -p ansible/inventories/bootstrap ansible/inventories/dev
        aws s3 cp s3://project01-tfstate-bucket-mk/bootstrap/inventory.yml ansible/inventories/bootstrap/inventory.yml
        aws s3 cp s3://project01-tfstate-bucket-mk/dev/inventory.yml ansible/inventories/dev/inventory.yml


    # 5. ec2가 ssh 접속을 허용할 때 까지 시간이 필요하여 기다리기
    - name: Wait for Bastion SSH ready
      shell: bash
      run: |
        BASTION_IP=$(aws ec2 describe-instances \
          --filters "Name=tag:Name,Values=*bastion*" "Name=instance-state-name,Values=running" \
          --query 'Reservations[].Instances[].PublicIpAddress' \
          --output text)

        echo "Waiting for SSH on port 22..."
        
        timeout 300 bash -c "until nc -zv $BASTION_IP 22 2>/dev/null; do echo 'Waiting...'; sleep 5; done"
        sleep 10