terraform_version: "1.14.9"
terraform_arch: "amd64"
terraform_os: "linux"
terraform_zip: "terraform_{{ terraform_version }}_{{ terraform_os }}_{{ terraform_arch }}.zip"
terraform_url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/{{ terraform_zip }}"
was_terraform_dir: /home/ec2-user/was/ansible/roles/was/files/terraform