---
- name: "was jump를 위한 key copy"
  copy:
    src: "{{ was_key_local_path }}"
    dest: "/home/ec2-user/.ssh/project01-was-key.pem"
    owner: ec2-user
    group: ec2-user
    mode: "0600"

- name: "db jump를 위한 key copy"
  copy:
    src: "{{ db_key_local_path }}"
    dest: "/home/ec2-user/.ssh/project01-db-key.pem"
    owner: ec2-user
    group: ec2-user
    mode: "0600"

