- name: "aws CLI 다운"
  dnf:
    name: unzip
    state: present

- name: "aws CLI v2 다운"
  get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    dest: /tmp/awscliv2.zip

- name: "압축해제"
  unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp/
    remote_src: yes

- name: "설치"
  command: /tmp/aws/install