---
- import_tasks: bootstrap.yml
- import_tasks: swapon.yml
- import_tasks: nginx.yml
- import_tasks: ansible.yml
- import_tasks: terraform.yml
- import_tasks: prometheus.yml
- import_tasks: grafana.yml
- import_tasks: awscli.yml
- import_tasks: swapoff.yml
- import_tasks: copy_was.yml
  become: no
- import_tasks: copy_db.yml
- import_tasks: tmp_run.yml
  become: no