    - name: "unzip 다운"
      yum:
        name: unzip
        state: present

    - name: "테라폼 다운(zip)"
      get_url:
        url: "{{ terraform_url }}"
        dest: "/tmp/{{ terraform_zip }}"
        mode: '0644'

    - name: "압축해제"
      unarchive:
        src: "/tmp/{{ terraform_zip }}"
        dest: "/usr/local/bin/"
        remote_src: yes
        mode: '0755'

    - name: "설치"
      command: terraform -version
      register: terraform_version_output

    - debug:
        var: terraform_version_output.stdout