"all":
  "children":
    "bastion":
      "hosts":
        "3.35.54.103":
          "ansible_ssh_private_key_file": "./project01-key-mgmt.pem"
          "ansible_user": "ec2-user"
    "was":
      "hosts":
        "10.0.10.183":
          "ansible_ssh_common_args": "-o ProxyCommand='ssh -W %h:%p -i ./project01-key-mgmt.pem
            ec2-user@3.35.54.103'"
          "ansible_ssh_private_key_file": "./project01-key-was.pem"
          "ansible_user": "ec2-user"