---
- name: "swapfile 존재 확인" # 있는지 먼저 확인하기 위함
  stat:
    path: /swapfile
  register: swapfile

- name: "swap 생성"
  when: not swapfile.stat.exists # 만약 없다면
  block:
    - name: "swapfile 생성"
      command: fallocate -l 1G /swapfile

    - name: "권한 설정"
      file:
        path: /swapfile
        mode: '0600'

    - name: "swap 생성"
      command: mkswap /swapfile

- name: "swap 활성화 여부 확인"
  command: swapon --show
  register: swap_status
  changed_when: false

- name: "swap 활성화"
  command: swapon /swapfile
  when: "'/swapfile' not in swap_status.stdout"
